version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
      - "4173:4173"
    restart: unless-stopped
    networks:
      - f_brain_network

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=production
    depends_on:
      - client
    networks:
      - f_brain_network

  monitoring:
    build:
      context: ./Monitoring
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
      - "3000:3000"
    networks:
      - f_brain_network

  proxy:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - client
      - server
    networks:
      - f_brain_network

networks:
  f_brain_network:
    driver: bridge

