version: '3.8'

services:
  client:
    build: ./client
    ports:
      - "5173:5173"

  server:
    build: ./server
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  celery:
    build: ./server
    command: poetry run celery -A server worker --loglevel=info
    depends_on:
      - server
      - rabbitmq

  celery-exporter:
    image: danihodovic/celery-exporter
    command: ["--broker-url=amqp://guest:guest@rabbitmq:5672//"]
    ports:
      - "8888:8888"

  monitoring:
    build: ./monitoring
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    ports:
      - "3001:3000"

  proxy:
    image: nginx:alpine
    volumes:
      - ./proxy/default.conf:/etc/nginx/default.conf
    ports:
      - "8080:80"
    depends_on:
      - client
      - server
      - monitoring
