version: "3.8"

services:
  client:
    build: ./client
    ports:
      - "5173:5173"
      - "4173:4173"
    container_name: client

  server:
    build: ./server
    ports:
      - "8000:8000"
    container_name: server

  monitoring:
    build: ./monitoring
    ports:
      - "3000:3000"
    container_name: monitoring

  python-dev:
    build: ./LinuxTooling
    ports:
      - "2222:22"
    container_name: python-dev
    tty: true

  reverse-proxy:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - client
      - server
      - monitoring

