version: '3.8'

services:
  client:
    build: ./client
    ports:
      - "5173:5173"

  server:
    build: ./server
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      - DB_NAME=todo_db
      - DB_USER=todo_user
      - DB_PASSWORD=todo_pass
      - DB_HOST=postgres
      - DB_PORT=5432

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: todo_db
      POSTGRES_USER: todo_user
      POSTGRES_PASSWORD: todo_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always


  monitoring:
    build: ./monitoring
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    ports:
      - "3001:3000"

  proxy:
    image: nginx:alpine
    volumes:
      - ./proxy/default.conf:/etc/nginx/default.conf
    ports:
      - "8080:80"
    depends_on:
      - client
      - server
      - monitoring

volumes:
  postgres_data:
